server:
  port: 8066
fk:
  rocketmq:
    enable: true
    namesrv-addr: 192.168.170.129:9876,192.168.170.129:9877
    producer-max-message-size: 2048
    consumer-consume-thread-min: 1
    consumer-consume-thread-max: 2
    producer-retry-times-when-send-failed: 3