server:
  port: 8066
fk:
  rocketmq:
    enable: true
    namesrv-addr: 192.168.170.129:9876;192.168.170.129:9877
    producer-max-message-size: 2048
    producer-retry-times-when-send-failed: 3 #发送失败时重试发送3次
    producer-send-msg-timeout: 5000